
CREATE OR REPLACE VIEW view_lider_faccao
(LIDER, FACCAO, NACOES, PLANETAS, COM_ESPECIE, COM_NOME, PARTICIPA) AS
    SELECT F.LIDER, F.NOME, NF.NACAO, D.PLANETA, H.ESPECIE, H.COMUNIDADE, P.FACCAO 
        FROM NACAO_FACCAO NF JOIN FACCAO F
        ON NF.FACCAO = F.NOME
            LEFT JOIN DOMINANCIA D
            ON D.NACAO = NF.NACAO
                LEFT JOIN HABITACAO H
                ON H.PLANETA = D.PLANETA
                    LEFT JOIN PARTICIPA P
                    ON P.ESPECIE = H.ESPECIE AND P.COMUNIDADE = H.COMUNIDADE
        WHERE F.LIDER = '123.543.908-12' AND D.DATA_FIM >= TO_DATE(SYSDATE) OR D.DATA_FIM IS NULL;
    
SELECT * FROM view_lider_faccao;


CREATE OR REPLACE TRIGGER insert_participa
INSTEAD OF INSERT ON view_lider_faccao
FOR EACH ROW
    
BEGIN

    INSERT INTO PARTICIPA (FACCAO, ESPECIE, COMUNIDADE) VALUES (FACCAO, :new.Especie, :new.Comunidade);
    
END insert_update_participa;
